version: '3.9'

networks:
  docker-network:
    driver: bridge

services:
  server:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: docker_server
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/server
    networks:
      - docker-network