version: '3.1'

networks:
  odoo-network:
    driver: bridge

services:
  web:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo
    ports:
      - "8069:8069"
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoopwd
    volumes:
      - ./src:/var/lib/odoo
      # - ./config/:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - odoo-network
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoopwd
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql
    networks:
      - odoo-network
  adminer:
    container_name: odoo_adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - odoo-network

secrets:
  postgresql_password:
    file: odoo_pg_pass
