version: '3.9'

networks:
  docker-network:
    driver: bridge

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: docker_server
    env_file: .env
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/node-server
      - /usr/src/node-server/node_modules
    networks:
      - docker-network
  db:
    image: postgres:13
    env_file: ./.env
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/.postgres-data:/var/lib/postgresql
    networks:
      - docker-network