version: '3.9'

networks:
  docker-network:
    driver: bridge

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node_react_server
    # env_file: .env
    tty: true
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
    volumes:
      - ./application:/usr/src/node-server
      # - /usr/src/node-server/node_modules
    networks:
      - docker-network