version: "3.9"
networks:
  docker-django:
    driver: bridge

services:
  db:
    image: postgres
    container_name: django_db
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./docker/postgres/logs:/logs
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - docker-django
  web:
    build: .
    container_name: django_web
    volumes:
      - ./src:/backend-app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY="django-insecure-^k_j9!4y&bxmxuf*@pqg@y&z_3%a8vf5xx4oj)sujjr865ve4+"
    depends_on:
      - db
    networks:
      - docker-django
  adminer:
    container_name: django_adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - docker-django