version: '3.9'

networks:
  docker-laravel:
    driver: bridge

services:
  php:
    container_name: myapp_php
    build:
      context: ./docker/php
    # depends_on:
    #   - db
    networks:
      - docker-laravel
    volumes:
      - ./application/:/var/www

  nginx:
    container_name: myapp_nginx
    build:
      context: ./docker/nginx
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./application:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - docker-laravel
  
  db:
    container_name: myapp_mysql
    image: mysql:8.0.28
    env_file:
      - ./application/.env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_DB_PWD
