version: '3.9'

networks:
  docker-laravel:
    driver: bridge
    

services:
  php:
    container_name: myapp_php
    build:
      context: ./docker/php
    depends_on:
      - db
    networks:
      - docker-laravel
    volumes:
      - ./application/:/var/www

  nginx:
    container_name: myapp_nginx
    build:
      context: ./docker/nginx
    ports:
      - 8080:80
    depends_on:
      - php
    volumes:
      - ./application:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - docker-laravel
  
  db:
    container_name: myapp_mysql
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/.data:/var/lib/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf
    env_file:
      - ./application/.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'rootpwd'
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    networks:
      - docker-laravel

  phpmyadmin:
    container_name: myapp_phpmyadmin
    image: phpmyadmin:5.1.3
    ports:
      - 9300:80
    depends_on:
      - db
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: "db"
    networks:
      - docker-laravel

    